name: climate 
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch
  - pytorch-cuda=12.4
  - pandas
  - fastparquet
  - pyarrow
  - matplotlib
  - numpy
  - jupyter
  - ipython
  - h5py
  - netcdf4
  - xarray
